name: ChestShopXSOAP
main: ChestShop\ChestShop
version: 6.6.6
api: [4.0.0]
load: POSTWORLD
author: xSoap
description: follow me on instagram @irsan.agil
website: https://github.com/xSoapers
depend:
 - EconomyAPI
extensions:
- sqlite3
commands:
  id:
    description: Search item ID
    usage: "/id <itemname>"
    permission: chestshop.command.id
permissions:
  chestshop:
    default: op
    description: "Allows using all the ChestShop things"
    children:
      chestshop.command:
        default: op
        description: "Allows using all the PocketMoney commands"
        children:
          chestshop.command.id:
            default: true
            description: "Allows searching item ID"
      chestshop.makeshop:
        default: op
        description: "Allows making chest shops"
        children:
          chestshop.makeshop.1:
            default: true
            description: "Allows making 1 chest shop"
          chestshop.makeshop.unlimited:
            default: true
            description: "Allows making unlimited chest shops"
      chestshop.deleteshop:
        default: op
        description: "Allows deleting any chest shop"
